# Create a new user
POST http://localhost:5000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "caloriesBurnedDay": 1200,
  "email": "user2@notfound.local",
  "userName": "Ваня",
  "password": "123456",
  "gender": "female",
  "description": "1234ddddddddddddd56",
  "location": "Пионерская",
  "image": "dddddd",
  "dateBirth": "2012-02-22",
  "avatar": "ddddd",
  "role": "trainer",
  "trainingLevel": "новичок",
  "typeTraining": ["йога", "бокс"],
  "timeTraining": "10-30 мин",
  "caloriesBurnedTraining": 1200,
  "trainingReadiness": true,
  "merits": "string",
  "personalTraining": true,
  "certificates": ["mmm"]

}

###
# Create a new user
POST http://localhost:5000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user7@notfound.local",
  "userName": "Ваня",
  "password": "123456",
  "gender": "female",
  "location": "Пионерская",
  "dateBirth": "2012-02-22",
  "role": "trainer",
  "trainingLevel": "новичок",
  "typeTraining": ["йога", "бокс"],
  "merits": "string",
  "personalTraining": true
}

###

# Get user by ID
GET http://localhost:5000/api/auth/654f1d734fab265efc2857bd HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTU0YmIzMjRhNmY2NGJhNzE2MTdmNTgiLCJlbWFpbCI6InVzZXIxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJ1c2VyTmFtZSI6ItCS0LDQvdGPIiwiaWF0IjoxNzAwMDYzMjIxLCJleHAiOjE3MDAwNjM4MjF9.n-xht_-QQUhIRm6XQk_OveLM_xVYZ7bGk8Dj0rBjaK8

###

# Login user by email and password
POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user1@notfound.local",
  "password": "123456"
}

###

# Get new JWT pair
POST http://localhost:5000/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTU0YmIzMjRhNmY2NGJhNzE2MTdmNTgiLCJlbWFpbCI6InVzZXIxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJ1c2VyTmFtZSI6ItCS0LDQvdGPIiwidG9rZW5JZCI6IjBhMjBhYmM4LTc4ZWQtNDlmNy04NzI2LTUxZDExYmY0NjI2YSIsImlhdCI6MTcwMDA1MTgwNywiZXhwIjoxNzAwNjU2NjA3fQ.7nxHO_Xbvt_W073BBBZyjLixd42_Pylb4aDVan6CsRY

###

# Check user token
POST http://localhost:5000/api/auth/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTU0YmIzMjRhNmY2NGJhNzE2MTdmNTgiLCJlbWFpbCI6InVzZXIxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJ1c2VyTmFtZSI6ItCS0LDQvdGPIiwiaWF0IjoxNzAwMDUxODI4LCJleHAiOjE3MDAwNTI0Mjh9.D0iN_3BP3jXndZdRM4AHDIs5NdUIivrjwJMW2Xc9Ujw


###
