version: '3.5'
services:
  fitfriends.traning.mongo:
    image: mongo
    restart: always
    container_name: fitfriends.traning.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: fitfriends-traning

    ports:
      - 27016:27017

    volumes:
      - fitfriends.mongo.traning:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/fitfriends-traning --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  fitfriends.traning.mongo.ui:
    image: mongo-express
    restart: always
    container_name: fitfriends.traning.mongo.ui
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@fitfriends.traning.mongo:27017/

volumes:
  fitfriends.mongo.traning:
